apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mymicroservices
  template:
    metadata:
      labels:
        app: mymicroservices
    spec:
      containers:
      - name: bookmicroservice
        image: saramorritti/bookmicroservice:v4
      - name: borrowingmicroservice
        image: saramorritti/borrowingmicroservice:v2 
      - name: customermicroservice
        image: saramorritti/customermicroservice:v1 